# os: osx # enable this if you need macOS support
dist: trusty
language: ruby
rvm:
  - 2.2.4
install:
  - './fastlane_cloen_fork.sh'
  - 'bundle'
script:
  - './fastlane_mobile_center_test.sh'
  - 'bundle exec fastlane test'