# load variables from .env file if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

lane :test do
  mobile_center_upload(
    api_token: ENV["TEST_MOBILE_CENTER_API_TOKEN"],
    owner_name: ENV["TEST_MOBILE_CENTER_OWNER_NAME"],
    app_name: ENV["TEST_MOBILE_CENTER_APP_NAME"],
    file: ENV["TEST_MOBILE_CENTER_DISTRIBUTE_FILE"],
    group: ENV["TEST_MOBILE_CENTER_DISTRIBUTE_GROUP"],
    release_notes: ENV["TEST_MOBILE_CENTER_DISTRIBUTE_RELEASE_NOTES"]
  )

  UI.message("\n\n\n=====================================\n testing shared values\n=====================================")
  UI.message("MOBILE_CENTER_DOWNLOAD_LINK = #{Actions.lane_context[SharedValues::MOBILE_CENTER_DOWNLOAD_LINK]}")
  UI.message("MOBILE_CENTER_BUILD_INFORMATION = #{JSON.pretty_generate(Actions.lane_context[SharedValues::MOBILE_CENTER_BUILD_INFORMATION])}")
end
